# Generated by Django 2.2.1 on 2019-10-30 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('album_length', models.CharField(max_length=7)),
                ('album_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=100)),
                ('band_bio', models.TextField(default="Band's biography")),
                ('band_genre', models.CharField(max_length=50)),
                ('band_origin', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=50)),
                ('song_number', models.IntegerField()),
                ('song_length', models.CharField(max_length=6)),
                ('song_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Album')),
                ('song_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Band')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='album_band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Band'),
        ),
    ]
