# Generated by Django 2.2.1 on 2019-10-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_length',
            field=models.CharField(max_length=7),
        ),
    ]
