# Generated by Django 2.2.1 on 2019-10-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_auto_20191030_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_votes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='band',
            name='band_votes',
            field=models.IntegerField(default=1),
        ),
    ]
