# Generated by Django 2.2.1 on 2019-11-07 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20191030_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='band_photo',
            new_name='band_image',
        ),
    ]
