# Generated by Django 2.2.1 on 2022-04-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_song_song_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['name'], 'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ['name'], 'verbose_name': 'Banda', 'verbose_name_plural': 'Bandas'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['name'], 'verbose_name': 'Música', 'verbose_name_plural': 'Músicas'},
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_band',
            new_name='band',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_length',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_votes',
            new_name='votes',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_year',
            new_name='year',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='band_bio',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='band_genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='band_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='band_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='band_origin',
            new_name='origin',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='band_votes',
            new_name='votes',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_album',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_artist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_length',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_votes',
            new_name='votes',
        ),
    ]
